/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tec_key_Ptlmaner */

#ifndef _Included_com_tec_key_Ptlmaner
#define _Included_com_tec_key_Ptlmaner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tec_key_Ptlmaner
 * Method:    requestProcess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tec_key_Ptlmaner_requestProcess
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
